# Generated by Django 5.2.7 on 2025-10-12 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='deadline',
            field=models.DateField(blank=True, help_text='Deadline for report submission', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='period',
            field=models.CharField(blank=True, default='', help_text="Reporting period (e.g., 'January 2025', 'Q1 2025', 'Week 1')", max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged for Issues'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=15),
        ),
        migrations.AddField(
            model_name='report',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='submitted_to',
            field=models.ForeignKey(blank=True, help_text='Supervisor who receives this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
