# Generated by Django 5.2.7 on 2025-10-13 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_report_deadline_report_period_report_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='escalated_at',
            field=models.DateTimeField(blank=True, help_text='When this report was escalated', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='is_escalated',
            field=models.BooleanField(default=False, help_text='Whether this report has been escalated to next level'),
        ),
        migrations.AddField(
            model_name='report',
            name='parent_report',
            field=models.ForeignKey(blank=True, help_text='Parent report that this report was escalated from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_reports', to='core.report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged for Issues'), ('REJECTED', 'Rejected'), ('ESCALATED', 'Escalated to Next Level')], default='DRAFT', max_length=15),
        ),
    ]
