# Generated by Django 5.2.7 on 2025-11-02 01:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_report_hierarchy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'submitted_to'], name='report_status_receiver_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', '-created_at'], name='report_status_created_idx'),
        ),
    ]
