# Generated by Django 5.2.7 on 2026-08-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_report_report_status_receiver_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=350, unique=True)),
                ('category', models.CharField(choices=[('SCHOLARSHIP', 'Scholarships & Education'), ('GRANT', 'Grants & Funding'), ('JOB', 'Jobs & Employment'), ('TRAINING', 'Skills & Training'), ('EMPOWERMENT', 'Empowerment Programs'), ('FELLOWSHIP', 'Fellowships & Leadership')], default='GRANT', max_length=20)),
                ('provider', models.CharField(help_text='Who is providing this? (e.g. Federal Govt, NGO, Private Sector)', max_length=200)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True, help_text='Eligibility requirements (bullet points recommended)')),
                ('benefits', models.TextField(blank=True, help_text='What does it offer? (Funding amount, salary, etc.)')),
                ('application_link', models.URLField(blank=True, help_text='External link to apply')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open & Accepting Applications'), ('CLOSING_SOON', 'Closing Soon'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this opportunity on the homepage/hub top')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Opportunity',
                'verbose_name_plural': 'Opportunities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'category'], name='opp_status_cat_idx'), models.Index(fields=['deadline'], name='opp_deadline_idx')],
            },
        ),
    ]
