# Generated by Django 5.2.7 on 2026-08-22 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_opportunity'),
        ('leadership', '0002_alter_roledefinition_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvocacyCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issue', models.TextField(help_text='What is the core issue?')),
                ('background', models.TextField(help_text='Background context')),
                ('kpn_position', models.TextField(blank=True, help_text="KPN's official position")),
                ('actions_taken', models.TextField(blank=True, help_text='What actions have been taken?')),
                ('government_response', models.TextField(blank=True)),
                ('outcome', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='advocacy/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('WELFARE', 'Welfare & Relief'), ('VOLUNTEER', 'Volunteer Work'), ('PROJECT', 'Community Project'), ('HUMANITARIAN', 'Humanitarian Aid')], max_length=20)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='PLANNING', max_length=20)),
                ('description', models.TextField()),
                ('location_text', models.CharField(help_text='E.g., Birnin Kebbi Central Market', max_length=200)),
                ('people_reached', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='community/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(max_length=100)),
                ('reporter_phone', models.CharField(blank=True, max_length=20)),
                ('location_details', models.CharField(help_text='Specific location or village', max_length=200)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('incident_time', models.TimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('COMMUNITY', 'Community'), ('EDUCATION', 'Education'), ('AGRICULTURE', 'Agriculture'), ('HEALTH', 'Health'), ('SECURITY', 'Security'), ('INFRASTRUCTURE', 'Infrastructure'), ('MARKETS', 'Markets & Business'), ('YOUTH', 'Youth'), ('WOMEN', 'Women'), ('ENVIRONMENT', 'Environment'), ('HUMAN_INTEREST', 'Human Interest'), ('CULTURE', 'Culture'), ('TRADITIONAL', 'Traditional Institutions'), ('GOVERNMENT', 'Government & Governance'), ('EMERGENCY', 'Emergency'), ('OPPORTUNITY', 'Opportunity')], max_length=30)),
                ('what_happened', models.TextField()),
                ('who_was_involved', models.TextField(blank=True)),
                ('why_is_it_important', models.TextField(blank=True)),
                ('evidence_image', models.ImageField(blank=True, null=True, upload_to='reports/evidence/')),
                ('evidence_video', models.FileField(blank=True, null=True, upload_to='reports/evidence/videos/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('ESCALATED', 'Escalated'), ('APPROVED', 'Approved for Publication'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('info_status', models.CharField(blank=True, choices=[('VERIFIED', 'KPN VERIFIED'), ('CONFIRMED', 'KPN CONFIRMED'), ('DEVELOPING', 'KPN DEVELOPING'), ('ALERT', 'KPN COMMUNITY ALERT')], max_length=20)),
                ('internal_notes', models.TextField(blank=True, help_text='Not visible to public')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leadership.lga')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leadership.ward')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leadership.zone')),
            ],
        ),
    ]
