# Generated by Django 5.2.7 on 2026-08-22 16:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_advocacycampaign_communityinitiative_communityreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('SUCCESS', 'Success Story'), ('PROJECT', 'Community Project'), ('GOVERNMENT', 'Government Response'), ('EMPOWERMENT', 'Youth Empowerment'), ('TRAINING', 'Training Programme'), ('PARTNERSHIP', 'Partnership Achievement'), ('HUMANITARIAN', 'Humanitarian Activity')], max_length=30)),
                ('description', models.TextField()),
                ('people_impacted', models.PositiveIntegerField(blank=True, null=True)),
                ('communities_reached', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='impact_stories/')),
                ('date_achieved', models.DateField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Impact Story',
                'verbose_name_plural': 'Impact Stories',
                'ordering': ['-date_achieved', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='category',
            field=models.CharField(choices=[('SCHOLARSHIP', 'Scholarships & Education'), ('GRANT', 'Grants & Funding'), ('JOB', 'Jobs & Employment'), ('INTERNSHIP', 'Internships'), ('VOLUNTEER', 'Volunteer Opportunities'), ('ENTREPRENEURSHIP', 'Entrepreneurship'), ('TRAINING', 'Skills & Training'), ('EMPOWERMENT', 'Empowerment Programs'), ('FELLOWSHIP', 'Fellowships & Leadership')], default='GRANT', max_length=20),
        ),
    ]
