# Generated by Django 5.2.7 on 2026-09-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patron_type', models.CharField(choices=[('GRAND', 'Grand Patron'), ('PATRON', 'Patron')], default='PATRON', max_length=10)),
                ('full_name', models.CharField(max_length=200)),
                ('title', models.CharField(help_text='Official title/designation', max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patrons/')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = higher)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['patron_type', 'order', 'full_name'],
            },
        ),
    ]
