# Generated by Django 5.2.7 on 2026-09-19 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(unique=True)),
                ('request_count_today', models.PositiveIntegerField(default=0)),
                ('request_count_hour', models.PositiveIntegerField(default=0)),
                ('last_request_at', models.DateTimeField(blank=True, null=True)),
                ('last_hour_reset', models.DateTimeField(blank=True, null=True)),
                ('last_day_reset', models.DateField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_reason', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'AI Rate Limit',
                'verbose_name_plural': 'AI Rate Limits',
            },
        ),
        migrations.CreateModel(
            name='KPNMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('meeting_type', models.CharField(choices=[('STATE_EXECUTIVE', 'State Executive Meeting'), ('ZONAL', 'Zonal Meeting'), ('LGA', 'LGA Meeting'), ('WARD', 'Ward Meeting'), ('SPECIAL', 'Special / Emergency Meeting'), ('GENERAL', 'General Assembly')], default='STATE_EXECUTIVE', max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active / In Progress'), ('ENDED', 'Ended'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=15)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('telegram_message_id', models.BigIntegerField(blank=True, help_text='Message ID of the meeting announcement in the KPN Telegram channel', null=True)),
                ('telegram_chat_id', models.CharField(blank=True, help_text='Chat/group where the meeting attendance is managed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
                ('expected_participants', models.ManyToManyField(blank=True, help_text='KPN members expected to attend this meeting', related_name='expected_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KPN Meeting',
                'verbose_name_plural': 'KPN Meetings',
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(blank=True, help_text='Telegram user ID of the attendee', null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late (confirmed after grace period)'), ('ABSENT', 'Absent'), ('PARTIAL', 'Partial Attendance')], default='ABSENT', max_length=10)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When the member confirmed attendance via /present command', null=True)),
                ('joined_at', models.DateTimeField(blank=True, help_text='When member joined the group chat/voice (if technically measurable)', null=True)),
                ('left_at', models.DateTimeField(blank=True, help_text='When member left the group chat/voice (if technically measurable)', null=True)),
                ('measurable_duration_seconds', models.PositiveIntegerField(blank=True, help_text='Measurable participation duration in seconds (if technically available)', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='telegram_integration.kpnmeeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting Attendance',
                'verbose_name_plural': 'Meeting Attendance Records',
                'ordering': ['status', 'confirmed_at'],
                'unique_together': {('meeting', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TelegramAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_token', models.CharField(max_length=64, unique=True)),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, help_text='The KPN user initiating Telegram connection (null for new registrants)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram Auth State',
                'verbose_name_plural': 'Telegram Auth States',
                'indexes': [models.Index(fields=['state_token'], name='tg_state_idx'), models.Index(fields=['expires_at'], name='tg_state_exp_idx')],
            },
        ),
        migrations.CreateModel(
            name='TelegramMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(help_text='Permanent Telegram user ID. Never changes.', unique=True)),
                ('telegram_username', models.CharField(blank=True, help_text='Telegram @username (may change — supplementary only)', max_length=100)),
                ('telegram_first_name', models.CharField(blank=True, max_length=100)),
                ('telegram_last_name', models.CharField(blank=True, max_length=100)),
                ('telegram_photo_url', models.URLField(blank=True)),
                ('telegram_status', models.CharField(choices=[('creator', 'Creator'), ('administrator', 'Administrator'), ('member', 'Member'), ('restricted', 'Restricted'), ('left', 'Left'), ('kicked', 'Kicked/Banned'), ('not_member', 'Not a Member')], default='not_member', max_length=20)),
                ('is_verified', models.BooleanField(default=False, help_text='True only when Telegram confirms active channel membership')),
                ('first_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, help_text='When member was detected as having left the channel', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram Membership',
                'verbose_name_plural': 'Telegram Memberships',
                'indexes': [models.Index(fields=['telegram_user_id'], name='tg_user_id_idx'), models.Index(fields=['is_verified'], name='tg_verified_idx')],
            },
        ),
    ]
