# Generated by Django 5.2.7 on 2026-09-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Groq', 'DeepSeek', 'OpenRouter'", max_length=100)),
                ('protocol', models.CharField(choices=[('openrouter', 'OpenRouter'), ('openai_compatible', 'OpenAI Compatible'), ('google', 'Google Gemini')], default='openai_compatible', max_length=50)),
                ('base_url', models.URLField(blank=True, help_text="e.g., 'https://api.openai.com/v1' or 'https://api.groq.com/openai/v1'")),
                ('api_key', models.CharField(blank=True, help_text='Provider API Key (if blank, falls back to ENV var based on protocol)', max_length=255)),
                ('default_model', models.CharField(help_text="e.g., 'llama-3.1-8b-instant'", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this provider is enabled for fallback iteration')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number = higher priority during failover')),
                ('supports_chat', models.BooleanField(default=True)),
                ('supports_vision', models.BooleanField(default=False)),
                ('supports_embeddings', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Provider',
                'verbose_name_plural': 'AI Providers',
                'ordering': ['order', 'name'],
            },
        ),
    ]
