# Generated by Django 5.2.7 on 2026-09-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_integration', '0002_aiproviderconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text="e.g., 'KPN Constitution', 'Event Rules', 'Membership Duties'", max_length=200)),
                ('content', models.TextField(help_text='Paste the factual information here. The bot will read this to answer questions accurately.')),
                ('is_active', models.BooleanField(default=True, help_text="Turn off to temporarily hide this info from the bot's brain.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot Knowledge (Brain)',
                'verbose_name_plural': 'Bot Knowledge (Brain)',
                'ordering': ['topic'],
            },
        ),
    ]
