# Generated by Django 5.2.7 on 2025-10-12 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0001_initial'),
        ('staff', '0002_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinaryaction',
            name='legal_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disciplinaryaction',
            name='legal_opinion',
            field=models.TextField(blank=True, help_text="Legal Adviser's opinion on the disciplinary action"),
        ),
        migrations.AddField(
            model_name='disciplinaryaction',
            name='legal_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplinaryaction',
            name='legal_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_reviewed_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WomensProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('program_type', models.CharField(choices=[('TRAINING', 'Training & Skills Development'), ('EMPOWERMENT', 'Women Empowerment'), ('HEALTH', 'Health & Wellness'), ('ADVOCACY', 'Advocacy & Rights'), ('NETWORKING', 'Networking Event'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=15)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('target_participants', models.PositiveIntegerField(default=0, help_text='Expected number of participants')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_womens_programs', to=settings.AUTH_USER_MODEL)),
                ('lga', models.ForeignKey(blank=True, help_text='Leave blank for Zonal/State-level programs', null=True, on_delete=django.db.models.deletion.SET_NULL, to='leadership.lga')),
                ('participants', models.ManyToManyField(blank=True, related_name='womens_programs', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, help_text='Leave blank for State-level programs', null=True, on_delete=django.db.models.deletion.SET_NULL, to='leadership.zone')),
            ],
            options={
                'verbose_name': "Women's Program",
                'verbose_name_plural': "Women's Programs",
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
