# Generated by Django 5.2.7 on 2025-10-13 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0001_initial'),
        ('staff', '0003_disciplinaryaction_legal_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelfareProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('program_type', models.CharField(choices=[('HEALTH', 'Health Support'), ('FINANCIAL', 'Financial Assistance'), ('EDUCATION', 'Educational Support'), ('EMERGENCY', 'Emergency Relief'), ('SOCIAL', 'Social Welfare'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=15)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('target_beneficiaries', models.PositiveIntegerField(default=0, help_text='Expected number of beneficiaries')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('funds_disbursed', models.DecimalField(decimal_places=2, default=0, help_text='Amount already disbursed', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('beneficiaries', models.ManyToManyField(blank=True, related_name='welfare_programs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_welfare_programs', to=settings.AUTH_USER_MODEL)),
                ('lga', models.ForeignKey(blank=True, help_text='Leave blank for Zonal/State-level programs', null=True, on_delete=django.db.models.deletion.SET_NULL, to='leadership.lga')),
                ('zone', models.ForeignKey(blank=True, help_text='Leave blank for State-level programs', null=True, on_delete=django.db.models.deletion.SET_NULL, to='leadership.zone')),
            ],
            options={
                'verbose_name': 'Welfare Program',
                'verbose_name_plural': 'Welfare Programs',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='YouthProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('program_type', models.CharField(choices=[('TRAINING', 'Training & Skills Development'), ('WORKSHOP', 'Workshop'), ('MENTORSHIP', 'Mentorship Program'), ('ENTREPRENEURSHIP', 'Entrepreneurship'), ('LEADERSHIP', 'Leadership Development'), ('SPORTS', 'Sports & Recreation'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=15)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('target_participants', models.PositiveIntegerField(default=0, help_text='Expected number of participants')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('impact_report', models.TextField(blank=True, help_text='Summary of program impact and outcomes')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_youth_programs', to=settings.AUTH_USER_MODEL)),
                ('lga', models.ForeignKey(blank=True, help_text='Leave blank for Zonal/State-level programs', null=True, on_delete=django.db.models.deletion.SET_NULL, to='leadership.lga')),
                ('participants', models.ManyToManyField(blank=True, related_name='youth_programs', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, help_text='Leave blank for State-level programs', null=True, on_delete=django.db.models.deletion.SET_NULL, to='leadership.zone')),
            ],
            options={
                'verbose_name': 'Youth Program',
                'verbose_name_plural': 'Youth Programs',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
