# Generated by Django 5.2.7 on 2025-10-13 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0001_initial'),
        ('staff', '0004_welfareprogram_youthprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityOutreach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(help_text='Organization or community group name', max_length=300)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('engagement_type', models.CharField(choices=[('MEETING', 'Meeting'), ('PARTNERSHIP', 'Partnership Discussion'), ('EVENT', 'Community Event'), ('MEDIA', 'Media Engagement'), ('COLLABORATION', 'Collaboration'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('FOLLOW_UP', 'Follow-up Required')], default='PLANNED', max_length=15)),
                ('date', models.DateField(help_text='Date of outreach activity')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('purpose', models.TextField(help_text='Purpose of the outreach')),
                ('notes', models.TextField(blank=True, help_text='Details and outcomes of the engagement')),
                ('follow_up_date', models.DateField(blank=True, help_text='Date for follow-up action', null=True)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_outreach', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Community Outreach',
                'verbose_name_plural': 'Community Outreach Activities',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WardMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_type', models.CharField(choices=[('GENERAL', 'General Meeting'), ('EXECUTIVE', 'Executive Meeting'), ('EMERGENCY', 'Emergency Meeting'), ('PLANNING', 'Planning Session'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('agenda', models.TextField(blank=True, help_text='Meeting agenda and topics')),
                ('minutes', models.TextField(blank=True, help_text='Meeting minutes and decisions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ward_meetings', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward_meetings', to='leadership.ward')),
            ],
            options={
                'verbose_name': 'Ward Meeting',
                'verbose_name_plural': 'Ward Meetings',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WardMeetingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='staff.wardmeeting')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward_meeting_attendance', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_ward_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['member__last_name', 'member__first_name'],
                'unique_together': {('meeting', 'member')},
            },
        ),
        migrations.AddField(
            model_name='wardmeeting',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attended_ward_meetings', through='staff.WardMeetingAttendance', through_fields=('meeting', 'member'), to=settings.AUTH_USER_MODEL),
        ),
    ]
