# Generated by Django 5.2.7 on 2025-10-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_communityoutreach_wardmeeting_wardmeetingattendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Your Facebook profile URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Your Instagram profile URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='tiktok_url',
            field=models.URLField(blank=True, help_text='Your TikTok profile URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Your Twitter/X profile URL'),
        ),
    ]
