# Generated by Django 5.2.7 on 2025-10-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('leadership', '0001_initial'),
        ('staff', '0006_user_facebook_url_user_instagram_url_user_tiktok_url_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status'], name='user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='user_role_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status', 'role'], name='user_status_role_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['zone'], name='user_zone_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['lga'], name='user_lga_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['ward'], name='user_ward_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role_definition'], name='user_role_def_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='user_created_idx'),
        ),
    ]
