# Generated by Django 5.2.7 on 2025-10-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('leadership', '0001_initial'),
        ('staff', '0007_user_user_status_idx_user_user_role_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='user_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_role_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_zone_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_lga_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_ward_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_role_def_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='user_created_idx',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status', 'zone'], name='user_status_zone_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status', 'lga'], name='user_status_lga_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status', 'ward'], name='user_status_ward_idx'),
        ),
    ]
