# Generated by Django 5.2.7 on 2025-10-27 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0001_initial'),
        ('staff', '0008_remove_user_user_status_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief title for the announcement', max_length=200)),
                ('content', models.TextField(help_text='Announcement message')),
                ('scope', models.CharField(choices=[('GENERAL', 'General - All KPN Members'), ('ZONAL', 'Zonal - Specific Zone'), ('LGA', 'LGA - Specific LGA'), ('WARD', 'Ward - Specific Ward')], help_text='Who should receive this announcement', max_length=10)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Only active announcements are shown to users')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date (announcement will auto-deactivate)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('target_lga', models.ForeignKey(blank=True, help_text='Required for LGA scope', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='leadership.lga')),
                ('target_ward', models.ForeignKey(blank=True, help_text='Required for WARD scope', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='leadership.ward')),
                ('target_zone', models.ForeignKey(blank=True, help_text='Required for ZONAL scope - all LGAs in this zone will receive the announcement', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='leadership.zone')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'scope', 'target_zone'], name='ann_zone_idx'), models.Index(fields=['is_active', 'scope', 'target_lga'], name='ann_lga_idx'), models.Index(fields=['is_active', 'scope', 'target_ward'], name='ann_ward_idx'), models.Index(fields=['is_active', 'created_at'], name='ann_active_idx')],
            },
        ),
    ]
