# Generated by Django 5.2.7 on 2025-11-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('GENERAL', 'General Member'), ('STATE', 'State Executive'), ('ZONAL', 'Zonal Excos'), ('LGA', 'LGA Excos'), ('WARD', 'Ward Leaders')], default='GENERAL', max_length=10),
        ),
    ]
