# Generated by Django 5.2.7 on 2026-08-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_rename_role_definitions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20),
        ),
    ]
