# Generated by Django 5.2.7 on 2026-08-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_trusted_reporter',
            field=models.BooleanField(default=False, help_text='Manually granted by President or Director of Media & Communications'),
        ),
        migrations.AddField(
            model_name='user',
            name='reporter_level',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('COMMUNITY_REPORTER', 'Community Reporter'), ('TRUSTED_REPORTER', 'Trusted Reporter')], default='MEMBER', max_length=20),
        ),
    ]
