# Generated by Django 5.2.7 on 2025-10-11 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'LGA',
                'verbose_name_plural': 'LGAs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tier', models.CharField(choices=[('STATE', 'State Executive'), ('ZONAL', 'Zonal Coordinator'), ('LGA', 'LGA Coordinator'), ('WARD', 'Ward Leader')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('seat_number', models.PositiveIntegerField(help_text='Position number within tier (e.g., 1 for President)')),
            ],
            options={
                'ordering': ['tier', 'seat_number'],
                'unique_together': {('tier', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='leadership.lga')),
            ],
            options={
                'ordering': ['lga__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='lga',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lgas', to='leadership.zone'),
        ),
    ]
