# Generated by Django 5.2.7 on 2025-11-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roledefinition',
            name='tier',
            field=models.CharField(choices=[('STATE', 'State Executive'), ('ZONAL', 'Zonal Excos'), ('LGA', 'LGA Excos'), ('WARD', 'Ward Leaders')], max_length=10),
        ),
    ]
