# Generated by Django 5.2.7 on 2026-09-16 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0002_alter_roledefinition_tier'),
    ]

    operations = [
    ]
