# Generated by Django 5.2.7 on 2026-09-16 22:02

from django.db import migrations

def rename_role_titles(apps, schema_editor):
    RoleDefinition = apps.get_model('leadership', 'RoleDefinition')
    
    old_to_new = {
        'Legal & Ethics Adviser': 'Director of Legal Affairs & Ethics',
        'Director of Membership & Mobilization': 'Director of Community Engagement',
        'Assistant Director of Membership & Mobilization': 'Assistant Director of Community Engagement',
        'Auditor General': 'Director of Audit & Accountability',
        'Director of Welfare & Community Support': 'Director of Member Support & Welfare',
        'Director of Youth Development & Empowerment': 'Director of Youth Development',
        'Director of Women Development': "Director of Women's Development",
        'Assistant Director of Women Development': "Assistant Director of Women's Development",
        'Director of Public Relations & Community Engagement': 'Director of Public Relations & Partnerships',
        'Financial Secretary': 'Finance Operations Officer',
        'LGA Women Development Officer': "LGA Women's Development Officer",
        'LGA Community Support Officer': 'LGA Member Support Officer',
        'LGA Coordinator': 'LGA Network Lead',
        'Ward Coordinator': 'Ward Community Lead',
    }
    
    # First, handle duplicates. If the new title already exists (e.g. from a user creating it manually),
    # we need to reassign users from the old title to the new one, then delete the old role definition.
    User = apps.get_model('staff', 'User')
    
    for old_title, new_title in old_to_new.items():
        old_role = RoleDefinition.objects.filter(title=old_title).first()
        new_role_existing = RoleDefinition.objects.filter(title=new_title).first()
        
        if old_role and new_role_existing and old_role != new_role_existing:
            # Both exist. Move users to new_role and delete old_role
            User.objects.filter(role_definition=old_role).update(role_definition=new_role_existing)
            old_role.delete()
        elif old_role and not new_role_existing:
            # Only old exists, just rename it
            old_role.title = new_title
            old_role.save()

class Migration(migrations.Migration):

    dependencies = [
        ('leadership', '0003_fix_role_titles'),
    ]

    operations = [
        migrations.RunPython(rename_role_titles),
    ]
