# Generated by Django 5.2.7 on 2025-10-13 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('audit_period', models.CharField(help_text="e.g., 'Q1 2025' or 'January-March 2025'", max_length=100)),
                ('findings', models.TextField(help_text='Key findings from the audit')),
                ('recommendations', models.TextField(help_text='Recommendations for improvement')),
                ('compliance_status', models.CharField(blank=True, help_text='Overall compliance status', max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed')], default='DRAFT', max_length=15)),
                ('report_file', models.FileField(blank=True, help_text='Upload detailed audit report PDF', null=True, upload_to='audit_reports/')),
                ('review_notes', models.TextField(blank=True, help_text='Notes from the reviewer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_audits', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_audits', to=settings.AUTH_USER_MODEL)),
                ('submitted_to', models.ForeignKey(blank=True, help_text='Usually the President', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Report',
                'verbose_name_plural': 'Audit Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
