# Generated by Django 5.2.7 on 2025-11-02 10:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_auditreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditreport',
            index=models.Index(fields=['status', '-submitted_at'], name='audit_status_submitted_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status', '-created_at'], name='donation_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status', '-verified_at'], name='donation_status_verified_idx'),
        ),
    ]
