# Generated by Django 5.2.7 on 2025-11-02 10:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'author'], name='campaign_status_author_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', '-published_at'], name='campaign_status_pub_idx'),
        ),
    ]
