# Generated by Django 5.2.7 on 2026-08-21 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_campaign_status_author_idx_and_more'),
        ('leadership', '0002_alter_roledefinition_tier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.RemoveIndex(
            model_name='campaign',
            name='campaign_status_author_idx',
        ),
        migrations.AddField(
            model_name='campaign',
            name='category',
            field=models.CharField(choices=[('COMMUNITY', 'Community'), ('EDUCATION', 'Education'), ('AGRICULTURE', 'Agriculture'), ('HEALTH', 'Health'), ('SECURITY', 'Security'), ('INFRASTRUCTURE', 'Infrastructure'), ('MARKETS', 'Markets & Business'), ('YOUTH', 'Youth'), ('WOMEN', 'Women'), ('ENVIRONMENT', 'Environment'), ('HUMAN_INTEREST', 'Human Interest'), ('CULTURE', 'Culture'), ('TRADITIONAL', 'Traditional Institutions'), ('GOVERNANCE', 'Government & Governance'), ('EMERGENCY', 'Emergency'), ('CIVIC', 'Civic'), ('GENERAL', 'General')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='content_json',
            field=models.JSONField(blank=True, help_text='Block editor content stored as JSON', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='lga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='leadership.lga'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='location',
            field=models.CharField(blank=True, help_text='Specific community or location (e.g. Birnin Kebbi)', max_length=200),
        ),
        migrations.AddField(
            model_name='campaign',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Short summary for search engines (max 160 characters)', max_length=160),
        ),
        migrations.AddField(
            model_name='campaign',
            name='rejection_note',
            field=models.TextField(blank=True, help_text='Note from editor when returning article for revision'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='reporter_credit',
            field=models.CharField(choices=[('KPN_REPORTER', 'KPN Community Reporter'), ('KPN_CORRESPONDENT', 'KPN Ward Correspondent'), ('KPN_LGA', 'KPN LGA Network Team'), ('KPN_STATE', 'KPN State Team'), ('KPN_EDITORIAL', 'KPN Editorial Team')], default='KPN_REPORTER', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='subheadline',
            field=models.CharField(blank=True, help_text='Short deck/subheadline that appears below the main headline', max_length=500),
        ),
        migrations.AddField(
            model_name='campaign',
            name='verification_status',
            field=models.CharField(choices=[('DEVELOPING', 'KPN Developing'), ('CONFIRMED', 'KPN Confirmed'), ('VERIFIED', 'KPN Verified'), ('COMMUNITY_ALERT', 'KPN Community Alert')], default='DEVELOPING', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='leadership.ward'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Review'), ('PUBLISHED', 'Published'), ('REJECTED', 'Returned for Revision'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=10),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'category'], name='campaign_status_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'lga'], name='campaign_status_lga_idx'),
        ),
    ]
