"""
Django settings for KPN project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
import cloudinary
import cloudinary.uploader
import cloudinary.api
from dotenv import load_dotenv
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# No default fallback - must be set in environment variables for security
SECRET_KEY = config('SESSION_SECRET', default='django-insecure-dev-key-replace-in-production-123456789')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# --- START: New and Improved ALLOWED_HOSTS logic ---
# In DEBUG mode, allow all hosts for easier development
ALLOWED_HOSTS = []

# Render default domain
RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Custom domains
ALLOWED_HOSTS.extend([
    "kpn.com.ng",
    "www.kpn.com.ng",
    "127.0.0.1",
    "localhost"
])

# Allow Replit preview domains (optional)
REPLIT_DOMAINS = os.environ.get("REPLIT_DOMAINS")
if REPLIT_DOMAINS:
    ALLOWED_HOSTS.extend(REPLIT_DOMAINS.split(","))

# Development convenience
if DEBUG:
    ALLOWED_HOSTS = ["*"]

# Store these for CSRF_TRUSTED_ORIGINS
CSRF_TRUSTED_ORIGINS = []

# Render default domain
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f"https://{RENDER_EXTERNAL_HOSTNAME}")

# Custom domains
CSRF_TRUSTED_ORIGINS.extend([
    "https://kpn.com.ng",
    "https://www.kpn.com.ng",
])

# Replit preview domains
if REPLIT_DOMAINS:
    for domain in REPLIT_DOMAINS.split(","):
        CSRF_TRUSTED_ORIGINS.append(f"https://{domain}")
        CSRF_TRUSTED_ORIGINS.append(f"http://{domain}")

# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'corsheaders',
    'rest_api',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'cloudinary',

    # Security Apps
    'axes',
    
    # KPN Apps
    'core',
    'staff',
    'telegram_integration',
    'leadership',
    'campaigns',
    'donations',
    'media',
    'events',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',  # Brute-force protection
]

ROOT_URLCONF = 'KPN.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'staff.context_processors.announcements',
                'core.context_processors.notifications_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'KPN.wsgi.application'

# Database configuration
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Use PostgreSQL database from DATABASE_URL environment variable, fallback to sqlite3
DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL', f"sqlite:///{BASE_DIR / 'db.sqlite3'}"),
        conn_max_age=600,
        conn_health_checks=True,
    )
}

# Configure database connection pool settings for PostgreSQL
if DATABASES['default'].get('ENGINE') == 'django.db.backends.postgresql':
    if 'OPTIONS' not in DATABASES['default']:
        DATABASES['default']['OPTIONS'] = {}
    DATABASES['default']['OPTIONS']['connect_timeout'] = 30

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_TZ = True


# ======================================
# Static files (CSS, JavaScript, Images)
# ======================================
# For serving CSS/JS files in production
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ======================================
# Cloudinary Configuration
# ======================================

CLOUDINARY_CLOUD_NAME = config('CLOUDINARY_CLOUD_NAME', default='')
CLOUDINARY_API_KEY = config('CLOUDINARY_API_KEY', default='')
CLOUDINARY_API_SECRET = config('CLOUDINARY_API_SECRET', default='')

# Only configure Cloudinary if all credentials are provided
USE_CLOUDINARY = all([CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET])

if USE_CLOUDINARY:
    cloudinary.config(
        cloud_name=CLOUDINARY_CLOUD_NAME,
        api_key=CLOUDINARY_API_KEY,
        api_secret=CLOUDINARY_API_SECRET,
        secure=True
    )

# Django 4.2+ and 5.x media/static storage setup
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage" if USE_CLOUDINARY else "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# If not using Cloudinary, use local file storage
if not USE_CLOUDINARY:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

# WhiteNoise static file serving optimization
WHITENOISE_MAX_AGE = 31536000  # 1 year cache for static files
WHITENOISE_COMPRESSION = True
WHITENOISE_USE_FINDERS = False


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'staff.User'

# Login URLs
LOGIN_URL = 'staff:login'
LOGIN_REDIRECT_URL = 'staff:dashboard'
LOGOUT_REDIRECT_URL = 'core:home'

# Production site URL — used to build absolute URLs in emails (e.g. password reset links).
# Set this in your Render environment variables.
# Example: SITE_URL=https://kpn.com.ng
SITE_URL = config('SITE_URL', default='')

# Email Configuration
# ─────────────────────────────────────────────────────────────────────────────
# Lockally Sending API (primary email delivery for production)
LOCKALLY_API_KEY = config('LOCKALLY_API_KEY', default='')
LOCKALLY_API_URL = config('LOCKALLY_API_URL', default='')
LOCKALLY_FROM_EMAIL = config('LOCKALLY_FROM_EMAIL', default='')
LOCKALLY_FROM_NAME = config('LOCKALLY_FROM_NAME', default='KPN - Kebbi Progressive Network')

# Select email backend:
#   1. Lockally backend  — when LOCKALLY_API_KEY + LOCKALLY_API_URL are both set (production)
#   2. Console backend   — fallback for local development / when Lockally not configured
_lockally_configured = bool(LOCKALLY_API_KEY and LOCKALLY_API_URL)

EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='staff.lockally_backend.LockallyEmailBackend' if _lockally_configured
            else 'django.core.mail.backends.console.EmailBackend'
)

# SMTP settings retained for reference / manual override (not used when Lockally is active)
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
_email_port = config('EMAIL_PORT', default='587')
EMAIL_PORT = int(_email_port) if _email_port else 587
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@kpn.com.ng')

# Security Settings
# HTTPS/SSL Configuration
# Force SSL redirect off if we're on local dev (even if DEBUG is False in env)
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Cookie Security
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=not DEBUG, cast=bool)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = 3600  # 1 hour session timeout
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=not DEBUG, cast=bool)
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'

# Security Headers
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Password Validation - Simplified for easier memorable passwords
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 6,
        }
    },
]

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',  # AxesBackend should be first
    'django.contrib.auth.backends.ModelBackend',
]

# Django Axes Configuration - Brute Force Protection
AXES_FAILURE_LIMIT = 5  # Lock after 5 failed attempts
AXES_COOLOFF_TIME = 1  # Lock for 1 hour (in hours)
AXES_RESET_ON_SUCCESS = True
AXES_LOCKOUT_TEMPLATE = None  # Use default lockout behavior
AXES_LOCKOUT_PARAMETERS = [['username', 'ip_address']]
AXES_ENABLE_ACCESS_FAILURE_LOG = True
AXES_RESET_COOL_OFF_ON_FAILURE_DURING_LOCKOUT = True

# Telegram & AI Configuration
TELEGRAM_BOT_TOKEN = config('TELEGRAM_BOT_TOKEN', default='')
TELEGRAM_CHANNEL_ID = config('TELEGRAM_CHANNEL_ID', default='-1002364023770') # Can be @officialkpn or numeric ID
TELEGRAM_WEBHOOK_SECRET = config('TELEGRAM_WEBHOOK_SECRET', default='')
TELEGRAM_BOT_USERNAME = config('TELEGRAM_BOT_USERNAME', default='KPNKebbiBot')

OPENROUTER_API_KEY = config('OPENROUTER_API_KEY', default='')
OPENROUTER_MODEL = config('OPENROUTER_MODEL', default='google/gemma-3-27b-it:free')
GOOGLE_AI_API_KEY = config('GOOGLE_AI_API_KEY', default='')

AI_PROVIDERS = config('AI_PROVIDERS', default='openrouter,google')
AI_MAX_REQUESTS_PER_HOUR = config('AI_MAX_REQUESTS_PER_HOUR', default=20, cast=int)
AI_MAX_REQUESTS_PER_DAY = config('AI_MAX_REQUESTS_PER_DAY', default=100, cast=int)

TELEGRAM_REQUIRED_ROLE_TITLES = [
    'President', 'Vice President', 'General Secretary', 'Assistant General Secretary',
    'Director of Monitoring & Compliance', 'Director of Legal Affairs & Ethics',
    'Director of Finance', 'Finance Operations Officer',
    'Director of Community Engagement', 'Assistant Director of Community Engagement',
    'Director of Programmes & Events', 'Assistant Director of Programmes & Events',
    'Director of Audit & Accountability', 'Director of Member Support & Welfare',
    'Director of Youth Development', "Director of Women's Development",
    "Assistant Director of Women's Development", 'Director of Media & Communications',
    'Assistant Director of Media & Communications', 'Director of Public Relations & Partnerships',
    'Senatorial Director', 'Senatorial Administrative Officer', 'Senatorial Communications Officer',
    'LGA Network Lead',
    'Ward Community Lead',
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'KPN API',
    'DESCRIPTION': 'KPN Mobile App API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

CORS_ALLOW_ALL_ORIGINS = True

